# Generated by Django 5.1.4 on 2024-12-24 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('speciality', models.CharField(choices=[('General Physician', 'General Physician'), ('Gynecologist', 'Gynecologist'), ('Dermatologist', 'Dermatologist'), ('Paediatrician', 'Paediatrician'), ('Neurologist', 'Neurologist'), ('Gastroenterologists', 'Gastroenterologists')], max_length=200)),
                ('degree', models.CharField(max_length=200)),
                ('experience', models.IntegerField()),
                ('address1', models.CharField(max_length=300)),
                ('address2', models.CharField(max_length=300)),
                ('fees', models.IntegerField()),
                ('about', models.TextField(max_length=500)),
                ('photot', models.ImageField(blank=True, upload_to='users/%Y/%m/%d')),
            ],
        ),
    ]
