# Generated by Django 5.1.4 on 2024-12-24 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_doctor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='photot',
            new_name='photo',
        ),
    ]
