# Generated by Django 5.1.4 on 2025-01-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_appiontment_doctor_alter_appiontment_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='static/users/images/upload_area.png', upload_to='users/%Y/%m/%d'),
        ),
    ]
