# Generated by Django 5.1.4 on 2025-01-10 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_doctor_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
    ]
