# Generated by Django 5.1.4 on 2025-01-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_doctor_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='media/users/upload_area.png', upload_to='users/%Y/%m/%d'),
        ),
    ]
